In [2]:
import geopandas as gpd
import pandas as pd

In [3]:
%%time
df_keypoints = gpd.read_parquet('ust003_keypoints.parquet')
df_keypoints

CPU times: user 10.1 s, sys: 3.79 s, total: 13.9 s
Wall time: 11.7 s

,trace_id,frame_index,type,position,x,y,z,r,geometry
0,7321240937826766161,0,1,0,-2.699846e+06,-4.294639e+06,3.853314e+06,8.896235,POINT Z (-122.15573 37.40606 43.95414)
1,7321240937826766161,0,1,0,-2.699846e+06,-4.294640e+06,3.853314e+06,9.918114,POINT Z (-122.15572 37.40606 43.89633)
2,7321240937826766161,0,1,0,-2.699848e+06,-4.294641e+06,3.853310e+06,9.068949,POINT Z (-122.15573 37.40602 43.91340)
3,7321240937826766161,0,1,0,-2.699847e+06,-4.294642e+06,3.853310e+06,9.797062,POINT Z (-122.15572 37.40602 43.87636)
4,7321240937826766161,1,0,0,-2.699846e+06,-4.294640e+06,3.853314e+06,9.270685,POINT Z (-122.15572 37.40606 43.86871)
...,...,...,...,...,...,...,...,...,...
9460428,15130015898775273847,1063,0,5,-2.698144e+06,-4.294283e+06,3.854833e+06,14.150174,POINT Z (-122.14158 37.42354 7.68938)
9460429,15130015898775273847,1063,4,1,-2.698144e+06,-4.294283e+06,3.854833e+06,14.489495,POINT Z (-122.14159 37.42354 7.69091)
9460430,15130015898775273847,1063,4,1,-2.698144e+06,-4.294283e+06,3.854833e+06,15.147362,POINT Z (-122.14158 37.42355 7.67815)
9460431,15130015898775273847,1063,4,2,-2.698141e+06,-4.294290e+06,3.854826e+06,10.905994,POINT Z (-122.14151 37.42347 7.65865)
9460432,15130015898775273847,1063,4,2,-2.698141e+06,-4.294290e+06,3.854827e+06,11.492822,POINT Z (-122.14151 37.42347 7.64534)

In [5]:
%%time
df_traces = gpd.read_parquet('ust003_traces.parquet')
df_traces

CPU times: user 2.08 s, sys: 706 ms, total: 2.78 s
Wall time: 2.4 s

,trace_id,frame_index,edge_id,x,y,z,geometry
0,7321240937826766161,0,029d43ab-f8b9-4a50-a5b3-fb28e3a21d5b,-2.699855e+06,-4.294636e+06,3.853312e+06,POINT Z (-122.15583 37.40604 44.16407)
1,7321240937826766161,1,029d43ab-f8b9-4a50-a5b3-fb28e3a21d5b,-2.699854e+06,-4.294636e+06,3.853313e+06,POINT Z (-122.15582 37.40604 44.14079)
2,7321240937826766161,2,029d43ab-f8b9-4a50-a5b3-fb28e3a21d5b,-2.699853e+06,-4.294636e+06,3.853313e+06,POINT Z (-122.15581 37.40604 44.11980)
3,7321240937826766161,3,029d43ab-f8b9-4a50-a5b3-fb28e3a21d5b,-2.699853e+06,-4.294636e+06,3.853313e+06,POINT Z (-122.15581 37.40604 44.09939)
4,7321240937826766161,4,029d43ab-f8b9-4a50-a5b3-fb28e3a21d5b,-2.699852e+06,-4.294637e+06,3.853313e+06,POINT Z (-122.15580 37.40604 44.07779)
...,...,...,...,...,...,...,...
1585838,15130015898775273847,1060,3617c7ba-c830-4d88-9043-d4432a021165,-2.698153e+06,-4.294289e+06,3.854819e+06,POINT Z (-122.14164 37.42339 7.80482)
1585839,15130015898775273847,1061,3617c7ba-c830-4d88-9043-d4432a021165,-2.698152e+06,-4.294289e+06,3.854820e+06,POINT Z (-122.14163 37.42339 7.79820)
1585840,15130015898775273847,1062,3617c7ba-c830-4d88-9043-d4432a021165,-2.698152e+06,-4.294289e+06,3.854821e+06,POINT Z (-122.14162 37.42340 7.79008)
1585841,15130015898775273847,1063,3617c7ba-c830-4d88-9043-d4432a021165,-2.698151e+06,-4.294289e+06,3.854822e+06,POINT Z (-122.14161 37.42341 7.78263)
1585842,15130015898775273847,1064,3617c7ba-c830-4d88-9043-d4432a021165,-2.698150e+06,-4.294289e+06,3.854822e+06,POINT Z (-122.14161 37.42342 7.77758)

In [16]:
df_traces = df_traces.dropna(subset=['edge_id'])

In [19]:
dft = df_traces.loc[df_traces['edge_id'].str.match('029d43ab-f8b9-4a50-a5b3-fb28e3a21d5b')]

In [20]:
%%time
df_keypoints.loc[df_keypoints['trace_id'].isin(dft['trace_id']) & df_keypoints['frame_index'].isin(dft['frame_index'])]

CPU times: user 142 ms, sys: 21.2 ms, total: 163 ms
Wall time: 161 ms

,trace_id,frame_index,type,position,x,y,z,r,geometry
0,7321240937826766161,0,1,0,-2.699846e+06,-4.294639e+06,3.853314e+06,8.896235,POINT Z (-122.15573 37.40606 43.95414)
1,7321240937826766161,0,1,0,-2.699846e+06,-4.294640e+06,3.853314e+06,9.918114,POINT Z (-122.15572 37.40606 43.89633)
2,7321240937826766161,0,1,0,-2.699848e+06,-4.294641e+06,3.853310e+06,9.068949,POINT Z (-122.15573 37.40602 43.91340)
3,7321240937826766161,0,1,0,-2.699847e+06,-4.294642e+06,3.853310e+06,9.797062,POINT Z (-122.15572 37.40602 43.87636)
4,7321240937826766161,1,0,0,-2.699846e+06,-4.294640e+06,3.853314e+06,9.270685,POINT Z (-122.15572 37.40606 43.86871)
...,...,...,...,...,...,...,...,...,...
1634221,5344438130974409701,30,1,0,-2.699816e+06,-4.294675e+06,3.853293e+06,13.437387,POINT Z (-122.15523 37.40583 42.40666)
1634222,5344438130974409701,30,4,1,-2.699816e+06,-4.294675e+06,3.853293e+06,14.214468,POINT Z (-122.15522 37.40583 42.36982)
1634223,5344438130974409701,30,4,1,-2.699815e+06,-4.294676e+06,3.853292e+06,15.446317,POINT Z (-122.15521 37.40583 42.31179)
1634224,5344438130974409701,30,4,2,-2.699825e+06,-4.294673e+06,3.853290e+06,8.932298,POINT Z (-122.15532 37.40579 42.74128)
1634225,5344438130974409701,30,4,2,-2.699824e+06,-4.294674e+06,3.853289e+06,10.082058,POINT Z (-122.15531 37.40579 42.69092)